describe("To Purchase an item", () => {
    beforeEach(function () {
        cy.visit('https://demowebshop.tricentis.com/')
    })
    it('toSelectTheProduct', () => {
        cy.get('[href="/login"]').click()
        cy.get('#Email').should('be.empty').type('venky.kudumula@gmail.com')
        cy.get('#Password').should('be.empty').type('Venky@Kudumula1$')
        cy.xpath('//input[@class="button-1 login-button"]').should('be.enabled').click()
        cy.xpath('(//a[@href="/computers"])[1]').click().should('contain', 'Computers')
        cy.xpath('(//a[@href="/notebooks"])[4]').click().should('contain', 'Notebooks')
        cy.xpath('//input[@value="Add to cart"]').should('be.enabled').click()
        cy.get('[class="content"]').should('contain', 'The product has been added to your shopping cart')
        cy.xpath('(//span[@class="cart-label"])[1]').click()
        cy.get('[id="checkout"]').click()
        cy.xpath('//button[@title="close"]').click()
        cy.get('[id="termsofservice"]').click()
        cy.get('[id="checkout"]').click()
        cy.get('[id="BillingNewAddress_CountryId"]').select('41')
        cy.get('[id="BillingNewAddress_City"]').type('Secunderabad')
        cy.get('[id="BillingNewAddress_Address1"]').type('H.No:2-5, Vidyanagar colony, secunderabad')
        cy.get('[id="BillingNewAddress_Address2"]').type('Hyderabad')
        cy.get('[id="BillingNewAddress_ZipPostalCode"]').type('5000081')
        cy.get('[id="BillingNewAddress_PhoneNumber"]').type('9000811341')
        cy.xpath('(//input[@class="button-1 new-address-next-step-button"])[1]').click()
        cy.xpath('(//input[@title="Continue"])[2]').click()
        cy.get('[id="shippingoption_2"]').click()
        cy.get('[class="button-1 shipping-method-next-step-button"]').click()
        cy.get('[id="paymentmethod_2"]').click()
        cy.get('[class="button-1 payment-method-next-step-button"]').click()
        cy.get('[id="CreditCardType"]').select('MasterCard')
        cy.get('[name="CardholderName"]').type('venky kudumula')
        cy.get('[id="CardNumber"]').type('5123456789012346')
        cy.get('[id="ExpireMonth"]').select('5')
        cy.get('[id="CardCode"]').type('123')
        cy.get('[class="button-1 payment-info-next-step-button"]').click()
        cy.get('[class="button-1 confirm-order-next-step-button"]').click().should('have.text', 'Your order has been successfully processed!')
        cy.get('[class="details"]').then((orderid) => {
            cy.log(orderid)
        })
    })
})